---


#**TEMA 4.3: LISTAS SEGUNDA PARTE**
###ITZEL NIASANDIU ARANGUREN NAVARRO

---


#**Operaciones en listas**


####En Python encontramos varios tipos de métodos que pueden aplicarse a las listas:

*   Longitud
*   Concatenación
*   Repetición
*   Membresía
*   Máximo y mínimo
*   Suma
*   Conteo
*   Reversa
*   Ordenar
*   Filtrar
*   Mapeo
*   Copiar

#**Longitud**

---



####El método `len()` devuelve el número de elementos que se encuentran en la lista.

In [ ]:
# Ejemplo longitud de una lista
lista1 = [10, 20, 30, 40, 50]
lista2 = ['A','a','E','e','I','i','O','o','U','u']
print('Longitud de la lista 1: ', len(lista1))
print('Longitud de la lista 2: ', len(lista2))

Longitud de la lista 1:  5
Longitud de la lista 2:  10

#**Concatenación**


---


####La concatenación (+) enlaza dos o más listas y crea una nueva lista a partir de esta unión.

In [ ]:
# Ejemplo 1 de concatenación mismo tipo de datos
L1 = [1,2,3]
L2 = [4,5,6]
Nueva_Lista = L1 + L2
print('Nueva lista: ', Nueva_Lista)

# Ejemplo 2 de concatenación tipo de datos diferentes
L3 = ['A','B','C']
L4 = ['¡Hola Mundo!']
Lista_comb = L4 + L1 + L3 + L2
print('Lista combinada: ', Lista_comb)

Nueva lista:  [1, 2, 3, 4, 5, 6]
Lista combinada:  ['¡Hola Mundo!', 1, 2, 3, 'A', 'B', 'C', 4, 5, 6]

#**Repetición**

---



####La repetición (*) repite una misma lista el número de veces que se le indique y genera una nueva lista a partir de estos datos.

In [ ]:
# Ejemplo de repetición
L5 = ['A', 1, 'E', 2, 'I', 3]
Lista_repetida = L5 * 3
print(Lista_repetida)

['A', 1, 'E', 2, 'I', 3, 'A', 1, 'E', 2, 'I', 3, 'A', 1, 'E', 2, 'I', 3]

#**Membresía**


---


####La membresía `in` o `not in` evalúa si un elemento de la lista es igual a otro elemento externo y devuelve un valor verdadero o falso.

In [ ]:
# Ejemplo de membresía
Nombres = ['Vanessa','Gustavo','Miguel']
n = input('Nombre a buscar: ')
print(n,'pertenece a la lista de nombres: ', n in Nombres)

# n in Nombres Si se encuentra el nombre la salida es verdadera
# n not in Nombres Si se encuentra el nombre la salida es falsa

#**Máximo y Mínimo**


---


####La función `max()` devuelve el elemento de la lista con valor máximo.

####La función `min()` devuelve el elemento de la lista con valor mínimo.

####**Nota:** Para poder aplicar estos métodos es necesario que la lista contenga elementos del mismo tipo es decir números enteros con números reales, o letras con palabras.

In [ ]:
# Ejemplo de valor máximo
Num = [50, 8000, 465, 10300, 1, 0.86, 0.015]
Letra = ['W','G','X','A','Z']
print('El número con mayor valor de la lista es: ', max(Num))
print('La letra con mayor valor de la lista es: ', max(Letra))

# Ejemplo de valor mínimo
print('\nEl número con menor valor de la lista es: ', min(Num))
print('La letra con menor valor de la lista es: ', min(Letra))

# Ejemplo palabras con la misma letra
palabras = ['Avión', 'Astucia', 'Ardilla', 'Atenas']
print("\nLa palabra con menor valor de la lista es: ", min(palabras))
print("La palabra con mayor valor de la lista es: ", max(palabras))

El número con mayor valor de la lista es:  10300
La letra con mayor valor de la lista es:  Z

El número con menor valor de la lista es:  0.015
La letra con menor valor de la lista es:  A

La palabra con menor valor de la lista es:  Ardilla
La palabra con mayor valor de la lista es:  Avión

#**Suma**


---


####La función `sum()` suma todos los valores de un objeto iterable.

####**Nota:** Esta función solo se utiliza cuando tenemos objetos de tipo numérico.

In [ ]:
Num = [50, 100, 150, 200, 1000.65]
Suma_Num = sum(Num)
print("La suma total es: ", Suma_Num)

La suma total es:  1500.65

#**Conteo**


---
####La función `count()` devuelve el recuento de cuántas veces se produce un elemento en la lista.

In [ ]:
# Ejemplo de conteo
Lista = ['Lista', 'a', 15, 'e', 'Lista', 15, 987, 16, 15, 'i']
print('Conteo para Lista: ', Lista.count('Lista'))
print('Conteo para 15:    ', Lista.count(15))
print('Conteo para e:     ', Lista.count('e'))
print('Conteo para 3:     ', Lista.count(3))

Conteo para Lista:  2
Conteo para 15:     3
Conteo para e:      1
Conteo para 3:      0

#**Reversa**


---


####El método `reverse()` invierte los elementos de la lista.

In [ ]:
# Ejemplo lista al revés
L = [123, 'xyz', 856, 'abc', 'Joel', 97.65, 0.13]
print('Lista original: ', L)
L.reverse()
print("Lista en reversa: ", L)

Lista original:  [123, 'xyz', 856, 'abc', 'Joel', 97.65, 0.13]
Lista en reversa:  [0.13, 97.65, 'Joel', 'abc', 856, 'xyz', 123]

#**Ordenar**


---


####La función `sort()` ordena una lista de menor a mayor o alfabéticamente según el tipo de datos que contiene.

In [ ]:
# Ejemplo 1 ordenar una lista de menor a mayor
LN = [123, 15, 1, 856, 97.65, 0.13, 0.025, 4]
print('Lista original: ', LN)
LN.sort()
print("Lista ordenada: ", LN)

# Ejemplo 2 ordenar una lista de forma alfabética
LA = ['Vanessa','Gustavo','Víctor','Arturo','Itzel','Gabriela','Miguel','Ariana']
print('\nLista original: ', LA)
LA.sort()
print("Lista ordenada: ", LA)

Lista original:  [123, 15, 1, 856, 97.65, 0.13, 0.025, 4]
Lista ordenada:  [0.025, 0.13, 1, 4, 15, 97.65, 123, 856]

Lista original:  ['Vanessa', 'Gustavo', 'Víctor', 'Arturo', 'Itzel', 'Gabriela', 'Miguel', 'Ariana']
Lista ordenada:  ['Ariana', 'Arturo', 'Gabriela', 'Gustavo', 'Itzel', 'Miguel', 'Vanessa', 'Víctor']

#**Filtrar**

---

####El método **`filter()`** selecciona elementos de un iterable (lista, tupla, etc.) basándose en la salida de una **función**.

####El proceso de la **función** se aplica a cada elemento del iterable y si devuelve un valor **`True`**, el elemento es seleccionado por la función **`filter()`** y guardado en un objeto iterable.

####**Sintaxis:**


```
variable = filter(función, lista)
```

In [2]:
def par(numero): #Función que verifica si un número es par
  if numero % 2 == 0:
    return True #Si el número es par devuelve un valor verdadero
  else:
    return False

#Programa principal
x = 0
num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] #Lista a filtrar
num_par = filter(par, num) #Filtro la lista y obtengo los números pares
#print(num_par)
lista_num_par = list(num_par) #Transformo el objeto realizado por filter a una lista
print(lista_num_par)

[2, 4, 6, 8, 10]

#**Mapeo**

---

####El método **`map()`** aplica una función determinada a cada elemento de un iterable (lista, tupla, etc.) y devuelve un iterador que contiene los resultados.

####**Sintaxis:**


```
variable = map(función, lista)
```

In [ ]:
def cuadrado(numero): #Función que devuelve el cuadrado de un número
  return numero**2

#Programa principal
num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] #Lista a mapear
cuadrado_num = map(cuadrado, num) #Aplico la función cuadrado a cada elemento de la lista
lista_cuadrado_num = list(cuadrado_num) #Transformo el objeto iterable realizado por map a una lista
print(lista_cuadrado_num)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#**Copiar**


---



####Supongamos que se tiene la siguiente lista y se quiere hacer una copia de esta.

```
Nombres = ['Vanessa','Gustavo','Víctor','Arturo','Itzel']
```

####Para hacer una copia de un dato de tipo lista se requiere hacer uso de la función `copy()`. No se puede hacer una copia de forma directa con el operador de asignación (=) como en el siguiente ejemplo:

```
Nombres2 = Nombres
```

####Al hacer esto la variable `Nombres2` si guarda los datos de la lista original pero cualquier cambio que se haga en la lista original también se verá reflejado en la lista que "copiamos" mediante el operador de asignación (=). Este caso se ejemplifica en el siguiente código:

In [ ]:
Nombres = ['Vanessa','Gustavo','Víctor','Arturo','Itzel']
Nombres2 = Nombres #Se hace una "copia" de la lista original mediante el operador de asignación =

#Se imprime la lista original y la "copia"
print("Lista Original: ", Nombres)
print("Lista Copia: ", Nombres2)

#Remuevo un nombre de la lista original
Nombres.remove("Gustavo")

#Se imprime a la lista original despúes de borrar un nombre y la "copia"
print("\nLista Original: ", Nombres)
print("Lista Copia: ", Nombres2)

Lista Original:  ['Vanessa', 'Gustavo', 'Víctor', 'Arturo', 'Itzel']
Lista Copia:  ['Vanessa', 'Gustavo', 'Víctor', 'Arturo', 'Itzel']

Lista Original:  ['Vanessa', 'Víctor', 'Arturo', 'Itzel']
Lista Copia:  ['Vanessa', 'Víctor', 'Arturo', 'Itzel']

####Note que en el código anterior al aplicar una modificación en la lista original, la lista **"copiada"** mediante el operador de asignación **(=)** también se ve afectada por los mismos cambios.

####Para poder copiar una lista y que esta no se vea afectada por los cambios de la lista original, se utilizará a la función `copy()`.

In [ ]:
#Función copy()
Nombres = ['Vanessa','Gustavo','Víctor','Arturo','Itzel']
Nombres2 = Nombres.copy() #Se hace una "copia" de la lista original mediante copy()

#Se imprime la lista original y la "copia"
print("Lista Original: ", Nombres)
print("Lista Copia: ", Nombres2)

#Remuevo un nombre de la lista original
Nombres.remove("Gustavo")

#Se imprime a la lista original despúes de borrar un nombre y a la copia
print("\nLista Original: ", Nombres)
print("Lista Copia: ", Nombres2)

Lista Original:  ['Vanessa', 'Gustavo', 'Víctor', 'Arturo', 'Itzel']
Lista Copia:  ['Vanessa', 'Gustavo', 'Víctor', 'Arturo', 'Itzel']

Lista Original:  ['Vanessa', 'Víctor', 'Arturo', 'Itzel']
Lista Copia:  ['Vanessa', 'Gustavo', 'Víctor', 'Arturo', 'Itzel']

#**Iteración de los elementos de una lista**

---

In [ ]:
# Ejemplo Iterar sobre los elementos de una lista

Frutas = ['Arándano', 'Granada', 'Melón', 'Manzana','Pera']
for elemento in Frutas:
  print(elemento)

Arándano
Granada
Melón
Manzana
Pera

In [ ]:
# Ejemplo Iterar sobre las posiciones de una lista por medio de index()

for elemento in Frutas:
  print(Frutas.index(elemento), elemento)

0 Arándano
1 Granada
2 Melón
3 Manzana
4 Pera

In [ ]:
# Ejemplo Iterar sobre las posiciones de una lista por medio de range() y len()

for indice in (range(len(Frutas))):
  print(indice, Frutas[indice])

0 Arándano
1 Granada
2 Melón
3 Manzana
4 Pera

In [ ]:
# Ejemplo de llenado de una lista mediante for

L = []
n = int(input("Cuantos elementos desea ingresar: "))
for i in (range(n)):
  dato = input("Ingrese el dato {}: ".format(i+1))
  L.append(dato)

print(L)

Cuantos elementos desea ingresar: 6
Ingrese el dato 1: 15
Ingrese el dato 2: 3
Ingrese el dato 3: Hola
Ingrese el dato 4: ñ
Ingrese el dato 5: nmg
Ingrese el dato 6: 96
['15', '3', 'Hola', 'ñ', 'nmg', '96']